#!/bin/bash
#
# (c) 2004-2007 Herve Fache
# License: GPL v2
#

PROGNAME=`basename $0`

REDUCTIONS_SIZE=320

# If we receive a path as argument, work within it
# Usually /var/www/photos
if [ -n "$1" ] && [ -d "$1" ]; then
    cd "$1"
fi
ROOT=$PWD

ALL_LANGUAGES=$ROOT/.languages

tr_getfield() {
    grep -e "^$2:" $ROOT/names/$1.text | sed "s/^$2: *//"
}

tr_languagename() {
    tr_getfield "$1" "languagename"
}

tr_back() {
    tr_getfield "$1" "back"
}

tr_backtotop() {
    tr_getfield "$1" "backtotop"
}

tr_photos() {
    tr_getfield "$1" "photos"
}

tr_generated() {
    tr_getfield "$1" "generated"
}

tr_slideshow() {
    tr_getfield "$1" "slideshow"
}

header() {
    echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">"
    echo "<html>"
    echo "<head>"
    echo "<meta NAME=\"Generator\" Content=\"My magic script\">"
    echo "<meta HTTP-EQUIV=\"Content-Type\" content=\"text/html; charset=utf-8\">"
    echo "<title>$1</title>"
    echo "</head>"
    echo "<body bgcolor=\"#333333\" text=\"#dddddd\" link=\"#95ddff\" vlink=\"#aaaaaa\" alink=\"#ff0000\">"
    echo ""
    echo "<a name=\"top\"></a>"
    echo "<table align=\"center\" bgcolor=\"#444444\" border=1 cellspacing=3 cellpadding=5>"
    echo "<tr><td align=\"center\"><h1>$1</h1>"
    if [ -n "$3" ]; then
        echo "<a href='$2'>$3</a>"
    fi
    echo "</td></tr>"
    echo "</table><p>&nbsp;</p>"
}

footer() {
    echo ""
    echo "</body>"
    echo "</html>"
}

slideshow_header() {
    echo "<script language=\"JavaScript\">"
    echo "//By Paul Davis - www.kaosweaver.com"
    echo "var j,d=\"\",l=\"\",m=\"\",p=\"\",q=\"\",z=\"\",list= new Array()"
}

slideshow_image() {
    echo "list[list.length]='$1';"
}

slideshow_footer() {
    echo "j=parseInt(Math.random()*list.length);"
    echo "j=(isNaN(j))?0:j;"
    echo "document.write(\"<img name='seqSlideShow' src='\"+list[j]+\"' border=0 >\");"
    echo "function seqSlideShow(t,l) {"
    echo "    x=document.seqSlideShow;"
    echo "    j=l;"
    echo "    j++;"
    echo "    if (j==list.length) j=0;"
    echo "    x.src=list[j];"
    echo "    setTimeout(\"seqSlideShow(\"+t+\",\"+j+\")\",t);"
    echo "}"
    echo "</script>"

    echo "<script language=\"JavaScript\"> seqSlideShow(2000,-1); </script>"
}

# Check needed tools
if ! which jhead > /dev/null 2>&1; then
    echo " -> jhead mising, aborting"
    exit 1
fi

# Main loop goes through all directories in view
echo "Create albums"
ls -1t | while read dir; do
    # If it contains an originals directory, it may be of interest
    if [ -d "$dir/originals" ]; then
        cd "$dir"
        echo " -> entering $dir"

        # Check that the directory contains photographs
        if ! ls originals/*.[jJ][pP][gG] > /dev/null 2>&1; then
            echo " --> no photograph files found, skipping"
            continue
        fi
        mkdir -p reductions

        # Make sure permissions and date are correct
        echo " --> checking originals"
        ls -tr originals/*.[jJ][pP][gG] | while read ORIGINAL; do
            IMAGE=`basename "$ORIGINAL"`
            echo " ---> checking $IMAGE"

            ORIGINAL_STAMP="originals/.$IMAGE"
            if [ ! -e "$ORIGINAL_STAMP" -o ! -s "$ORIGINAL_STAMP" ]; then
                # Make sure the permissions are correct and repair file time
                if chmod 644 "$ORIGINAL" && jhead -ft "$ORIGINAL" > /dev/null; then
                    jhead -c "$ORIGINAL" | cut -d '"' -f 3 | cut -d ' ' -f 2 > "$ORIGINAL_STAMP"
                fi
            fi

            # Check reduction dimensions
            REDUCTION="reductions/$IMAGE"
            REDUCTION_STAMP="reductions/.$IMAGE"
            if [ -e "$REDUCTION" ]; then
                if [ ! -e "$REDUCTION_STAMP" -o ! -s "$REDUCTION_STAMP" ]; then
                    jhead -c "$REDUCTION" | cut -d '"' -f 3 | cut -d ' ' -f 2 > "$REDUCTION_STAMP"
                fi
                REDUCTION_DIMENSIONS=`cat "$REDUCTION_STAMP"`
                REDUCTION_WIDTH=${REDUCTION_DIMENSIONS/x*/}
                REDUCTION_HEIGHT=${REDUCTION_DIMENSIONS/*x/}
                if [[ $REDUCTION_WIDTH > $REDUCTION_HEIGHT ]]; then
                    # Landscape
                    REDUCTION_DIMENSION=${REDUCTION_DIMENSIONS/x*/}
                else
                    # Portrait
                    REDUCTION_DIMENSION=${REDUCTION_DIMENSIONS/*x/}
                fi
                if [ "$REDUCTION_DIMENSION" != "$REDUCTIONS_SIZE" ]; then
                    echo " ---> scheduling for re-creation"
                    unset REDUCTION_ISVALID
                else
                    REDUCTION_ISVALID="yes"
                fi
            else
                unset REDUCTION_ISVALID
            fi

            # Create reduction
            if [ -z "$REDUCTION_ISVALID" ]; then
                echo " ---> creating reduction"
                ORIGINAL_DIMENSIONS=`cat "$ORIGINAL_STAMP"`
                ORIGINAL_WIDTH=${ORIGINAL_DIMENSIONS/x*/}
                ORIGINAL_HEIGHT=${ORIGINAL_DIMENSIONS/*x/}
                if [[ $ORIGINAL_WIDTH > $ORIGINAL_HEIGHT ]]; then
                    convert -resize $REDUCTIONS_SIZE "$ORIGINAL" .image
                else
                    convert -resize x$REDUCTIONS_SIZE "$ORIGINAL" .image
                fi
                rm -f "$REDUCTION" "$REDUCTION_STAMP"
                mv .image "$REDUCTION"
                jhead -c "$REDUCTION" | cut -d '"' -f 3 | cut -d ' ' -f 2 > "$REDUCTION_STAMP"
            fi
        done

        # Make sure we have at least one language
        if  [ ! -r languages ]; then
            echo en > languages
        fi
        LANGUAGES=`cat languages`

        # Language support
        ln -sf $ROOT/flags
        ln -sf $ROOT/index.html index.html

        # Create index
        echo " --> checking indexes"
        for LANGUAGE in $LANGUAGES; do
            echo $LANGUAGE >> $ALL_LANGUAGES
            TITLES="titles-$LANGUAGE.text"
            if [ -r $LANGUAGE/index.html -a $TITLES -ot $LANGUAGE/index.html ]; then
                continue
            fi

            echo -n " ---> creating index for language $LANGUAGE"
            LANGUAGE_NAME=`tr_languagename "$LANGUAGE"`
            if [ -n "$LANGUAGE_NAME" ]; then
                echo " ($LANGUAGE_NAME)"
            else
                echo
            fi

            # Create photos titles file
            mkdir -p $LANGUAGE

            TITLES="titles-$LANGUAGE.text"
            if [ ! -r "$TITLES" ]; then
                touch "$TITLES"
            fi

            # Add title
            TITLE=`grep -m1 -e "^TITLE:" "$TITLES"`
            if [ -z "$TITLE" ]; then
                echo "TITLE: untitled" >> "$TITLES"
                TITLE="untitled"
            else
                TITLE=`echo $TITLE | sed "s/^TITLE: *//"`
            fi

            # Create header (and file)
            header "$TITLE" "../../$LANGUAGE" "`tr_back "$LANGUAGE"`" > $LANGUAGE/.index

            # Links to other languages
            echo "<table align=\"center\"><tr><td align=\"center\" bgcolor=\"#444444\">" >> $LANGUAGE/.index
            for OTHER_LANGUAGE in $LANGUAGES; do
                if [ "$OTHER_LANGUAGE" != "$LANGUAGE" ]; then
                    OTHER_LANGUAGE_NAME=`tr_languagename "$OTHER_LANGUAGE"`
                    echo "<a href=\"../$OTHER_LANGUAGE\"><img src=\"../flags/$OTHER_LANGUAGE.gif\" width=28 height=15 alt=\"[$OTHER_LANGUAGE]\" title=\"$OTHER_LANGUAGE_NAME\"></a>" >> $LANGUAGE/.index
                fi
            done
            echo "</tr></td></table><p>&nbsp;</p>" >> $LANGUAGE/.index

            # Slideshow
            echo "<table align=\"center\" border=1 cellspacing=0 cellpadding=3>" >> $LANGUAGE/.index
            echo "<tr><td align=\"center\" bgcolor=\"#444444\"><b>`tr_slideshow "$LANGUAGE"`</b></tr></td>" >> $LANGUAGE/.index
            echo "<tr><td align=\"center\" bgcolor=\"#444444\" height=`expr $REDUCTIONS_SIZE + 10` width=`expr $REDUCTIONS_SIZE + 10`>" >> $LANGUAGE/.index
            slideshow_header >> $LANGUAGE/.index
            ls -tr originals/*.[jJ][pP][gG] | while read ORIGINAL; do
                IMAGE=`basename "$ORIGINAL"`
                REDUCTION="reductions/$IMAGE"
                slideshow_image "../$REDUCTION" >> $LANGUAGE/.index
            done
            slideshow_footer >> $LANGUAGE/.index
            echo "</tr></td></table><p>&nbsp;</p>" >> $LANGUAGE/.index

            # Album
            ls -tr originals/*.[jJ][pP][gG] | while read ORIGINAL; do
                IMAGE=`basename "$ORIGINAL"`
                REDUCTION="reductions/$IMAGE"
                echo "<table align=\"center\" border=1 cellspacing=0 cellpadding=3><tr><td align=\"center\" bgcolor=\"#444444\">" >> $LANGUAGE/.index
                echo "<a href=\"../$ORIGINAL\"><img src=\"../$REDUCTION\" alt=\"$IMAGE\" title=\"$IMAGE\"></a>" >> $LANGUAGE/.index
                IMAGE_COMMENT=`grep -m1 -e "^$IMAGE:" "$TITLES"`
                if [ -z "$IMAGE_COMMENT" ]; then
                    echo "$IMAGE: untitled" >> "$TITLES"
                    IMAGE_COMMENT="untitled"
                else
                    IMAGE_COMMENT=`echo $IMAGE_COMMENT | sed "s%^$IMAGE:%%"`
                fi
                BACKTOTOP=`tr_backtotop $LANGUAGE`
                echo "<p align=\"center\"><b>$IMAGE_COMMENT</b><br><i>(Date: `date +"%F %R %Z" -r "$ORIGINAL"`, Size: `du --si "$ORIGINAL" | cut -f 1`)</i><br><a href=\"#top\">$BACKTOTOP</a></p>" >> $LANGUAGE/.index
                echo "</tr></td></table><p>&nbsp;</p>" >> $LANGUAGE/.index
            done

            # Add footer
            footer >> $LANGUAGE/.index

            # Put new files online
            mv $LANGUAGE/.index $LANGUAGE/index.html
        done

	ORIGINAL=`ls -1tr originals/*.[jJ][pP][gG] | tail -1`
        touch -r "$ORIGINAL" .
        cd ..
    fi
done

# Create languages file
sort $ALL_LANGUAGES | uniq > languages
rm -f $ALL_LANGUAGES

# Now that the directory dates are set, fill in the main index file
echo "Create album indexes"
LANGUAGES=`cat languages`
for LANGUAGE in $LANGUAGES; do
    mkdir -p $LANGUAGE
    echo " -> language $LANGUAGE"

    header "`tr_photos "$LANGUAGE"`" ".." "`tr_back "$LANGUAGE"`" > $LANGUAGE/.index

    # Re-offer language selection
    echo "<table align=\"center\"><tr><td align=\"center\" bgcolor=\"#444444\">" >> $LANGUAGE/.index
    for OTHER_LANGUAGE in $LANGUAGES; do
        if [ "$OTHER_LANGUAGE" != "$LANGUAGE" ]; then
            OTHER_LANGUAGE_NAME=`tr_languagename "$OTHER_LANGUAGE"`
            echo "<a href=\"../$OTHER_LANGUAGE\"><img src=\"../flags/$OTHER_LANGUAGE.gif\" width=28 height=15 alt=\"[$OTHER_LANGUAGE]\" title=\"$OTHER_LANGUAGE_NAME\"></a>" >> $LANGUAGE/.index
        fi
    done
    echo "</tr></td></table><p>&nbsp;</p>" >> $LANGUAGE/.index

    echo "<table align=\"center\"><tr><td>" >> $LANGUAGE/.index
    ls -1tr | while read dir; do
        if [ ! -r "$dir/languages" ]; then
            continue
        fi
        TITLES="$dir/titles-$LANGUAGE.text"
        if [ ! -r "$TITLES" ]; then
            # Default to English
            USED_LANGUAGE=`head -1 "$dir/languages"`
            TITLES="$dir/titles-$USED_LANGUAGE.text"
        else
            USED_LANGUAGE="$LANGUAGE"
        fi
        if [ -d "$dir/$USED_LANGUAGE" ] && [ -r "$TITLES" ] && [ -r "$dir/$USED_LANGUAGE/index.html" ]; then
            echo " --> linking $dir/$USED_LANGUAGE"
            TITLE=`grep -e "^TITLE:" "$TITLES" | sed "s/^TITLE://"`
            echo "<h3>" >> $LANGUAGE/.index
            # Add flag if wrong language
            if [ "$LANGUAGE" != "$USED_LANGUAGE" ]; then
                USED_LANGUAGE_NAME=`tr_languagename "$USED_LANGUAGE"`
                echo " <img src=\"../flags/$USED_LANGUAGE.gif\" width=28 height=15 alt=\"[$USED_LANGUAGE]\" title=\"$USED_LANGUAGE_NAME\">" >> $LANGUAGE/.index
            fi
            echo "<a href=\"../$dir/$USED_LANGUAGE\">$TITLE</a>" >> $LANGUAGE/.index
            # Add flags for other languages
            for OTHER_LANGUAGE in `cat "$dir/languages"`; do
                if [ "$OTHER_LANGUAGE" != "$USED_LANGUAGE" ]; then
                    echo " ---> adding link to: $OTHER_LANGUAGE"
                    OTHER_LANGUAGE_NAME=`tr_languagename "$OTHER_LANGUAGE"`
                    echo " <a href=\"../$dir/$OTHER_LANGUAGE\"><img src=\"../flags/$OTHER_LANGUAGE.gif\" width=28 height=15 alt=\"[$OTHER_LANGUAGE]\" title=\"$OTHER_LANGUAGE_NAME\"></a>" >> $LANGUAGE/.index
                fi
            done
            echo "</h3>" >> $LANGUAGE/.index
        fi
    done
    echo "</td></tr></table>" >> $LANGUAGE/.index
    LINE=`tr_generated "$LANGUAGE"`
    echo "<p align=\"center\"><i>`echo $LINE | cut -d ' ' -f 1`: `date +"%F %R %Z" -r $LANGUAGE/.index` `echo $LINE | cut -d ' ' -f 2` <a href=\"$PROGNAME\">`echo $LINE | cut -d ' ' -f 3`</a> `echo $LINE | cut -d ' ' -f 4`</i></p>" >> $LANGUAGE/.index
    footer >> $LANGUAGE/.index

    # Put new file online
    mv $LANGUAGE/.index $LANGUAGE/index.html
done

# Now that the directory dates are set, fill in the main index file

header "&€^-!/%¥=*£+\$?" ".." "<---" > .index
echo "<table align=\"center\">" >> .index
# Flags
echo "<tr>" >> .index
for LANGUAGE in `cat languages`; do
    LANGUAGE_NAME=`tr_languagename "$LANGUAGE"`
    echo "<td align=\"center\"><a href=\"$LANGUAGE\"><img src=\"flags/$LANGUAGE.gif\" width=144 height=76 alt=\"$LANGUAGE_NAME\" title=\"$LANGUAGE_NAME\"></a></td>" >> .index
done
echo "</tr>" >> .index
# Names
echo "<tr>" >> .index
for LANGUAGE in `cat languages`; do
    LANGUAGE_NAME=`tr_languagename "$LANGUAGE"`
    echo "<td align=\"center\"><a href=\"$LANGUAGE\">$LANGUAGE_NAME</a></td>" >> .index
done
echo "</tr>" >> .index
echo "</table>" >> .index
footer >> .index

# Put new file online
mv .index index.html
