#!/bin/bash
#
# (c) 2006 Herve Fache
# License: GPL v2
#

PROGNAME=`basename $0`

MAX_DIMENSION=320

FILE=.index

# If we receive a path as argument, work within it
# Usually /srv/http/photos
if [ -n "$1" ] && [ -d "$1" ]; then
    cd "$1"
fi
ROOT=$PWD

ALL_LANGUAGES=$ROOT/.languages

header() {
    echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">"
    echo "<html>"
    echo "<head>"
    echo "<meta NAME=\"Generator\" Content=\"My magic script\">"
    echo "<meta HTTP-EQUIV=\"Content-Type\" content=\"text/html; charset=utf-8\">"
    echo "<title>$1</title>"
    echo "</head>"
    echo "<body bgcolor=\"#333333\" text=\"#dddddd\" link=\"#95ddff\" vlink=\"#aaaaaa\" alink=\"#ff0000\">"
    echo ""
    echo "<table align=\"center\" bgcolor=\"#444444\" border=1 cellspacing=3 cellpadding=5><tr><td><h1 align=\"center\">$TITLE</h1></td></tr></table><p>&nbsp;</p>"
}

footer() {
    echo ""
    echo "</body>"
    echo "</html>"
}

# Check needed tools
if ! which jhead > /dev/null 2>&1; then
    echo " -> jhead mising, aborting"
    exit 1
fi

# Main loop goes through all directories in view
echo "Create albums"
ls -1t | while read dir; do
    # If it contains an originals directory, it may be of interest
    if [ -d "$dir/HiQ" ]; then
        mv "$dir/HiQ" "$dir/originals"
    fi
    if [ -d "$dir/originals" ]; then
        cd "$dir"
        echo " -> entering $dir"

        # Check that the directory contains photographs
        if ! ls originals/*.[jJ][pP][gG] > /dev/null 2>&1; then
            echo " --> no photograph files found, skipping"
            continue
        fi
        mkdir -p reductions

        # Make sure permissions and date are correct
        echo " --> checking original files"
        cd originals
        for HIMAGE in `ls -tr *.[jJ][pP][gG]`; do
            HIMAGE_STAMP=".$HIMAGE"
            if [ ! -e "$HIMAGE_STAMP" ]; then
                # Make sure the permissions are correct and repair file time
                if chmod 644 "$HIMAGE" && jhead -ft "$HIMAGE" > /dev/null; then
                    jhead -c "$HIMAGE" | cut -d '"' -f 3 | cut -d ' ' -f 2 > "$HIMAGE_STAMP"
                fi
            fi
        done
        cd ..

        # Make sure we have at least one language
        if  [ ! -r languages ]; then
            echo en > languages
        fi
        LANGUAGES=`cat languages`

        # Language support
        ln -sf $ROOT/flags
        ln -sf $ROOT/index.html index.html

        # Create index
        for LANGUAGE in $LANGUAGES; do
            echo -n " --> creating index for language $LANGUAGE"
            if [ -r $ROOT/names/$LANGUAGE.text ]; then
                echo " (`cat $ROOT/names/$LANGUAGE.text`)"
            else
                echo
            fi
            echo $LANGUAGE >> $ALL_LANGUAGES

            # Create photos titles file
            mkdir -p $LANGUAGE

            TITLES="titles-$LANGUAGE.text"
            if [ ! -r "$TITLES" ]; then
                touch "$TITLES"
            fi

            # Add title
            TITLE=`grep -m1 -e "^TITLE:" "$TITLES"`
            if [ -z "$TITLE" ]; then
                echo "TITLE: untitled" >> "$TITLES"
                TITLE="untitled"
            else
                TITLE=`echo $TITLE | sed "s/^TITLE: *//"`
            fi

            # Create header (and file)
            header "$TITLE" > $LANGUAGE/.index
        done

        # Convert images
        for HIMAGE in `ls -tr originals/*.[jJ][pP][gG]`; do
            IMAGE=`basename "$HIMAGE"`
            HIMAGE_STAMP="originals/.$IMAGE"
            LIMAGE="reductions/$IMAGE"
            LIMAGE_STAMP="reductions/.$IMAGE"
            # Check reduction dimensions
            HIMAGE_DIMENSIONS=`cat "$HIMAGE_STAMP"`
            HIMAGE_WIDTH=${HIMAGE_DIMENSIONS/x*/}
            HIMAGE_HEIGHT=${HIMAGE_DIMENSIONS/*x/}
            echo -n " --> checking $IMAGE: "$HIMAGE_WIDTH"x"$HIMAGE_HEIGHT
            if [[ $HIMAGE_WIDTH > $HIMAGE_HEIGHT ]]; then
                echo " landscape"
            else
                echo " portrait"
            fi
            if [ ! -e "$LIMAGE_STAMP" ]; then
                jhead -c "$LIMAGE" | cut -d '"' -f 3 | cut -d ' ' -f 2 > "$LIMAGE_STAMP"
            fi
            if [ -e "$LIMAGE" ]; then
                LIMAGE_DIMENSIONS=`cat "$LIMAGE_STAMP"`
                if [[ $HIMAGE_WIDTH > $HIMAGE_HEIGHT ]]; then
                    # Landscape
                    LIMAGE_DIMENSION=${LIMAGE_DIMENSIONS/x*/}
                else
                    # Portrait
                    LIMAGE_DIMENSION=${LIMAGE_DIMENSIONS/*x/}
                fi
                if [ "$LIMAGE_DIMENSION" != "$MAX_DIMENSION" ]; then
                    echo " ---> scheduling for re-creation"
                    unset LIMAGE_ISVALID
                else
                    LIMAGE_ISVALID="yes"
                fi
            else
                unset LIMAGE_ISVALID
            fi

            # Create reduction
            if [ -z "$LIMAGE_ISVALID" ]; then
                echo " ---> creating thumbnail"
                if [[ $HIMAGE_WIDTH > $HIMAGE_HEIGHT ]]; then
                    convert -resize $MAX_DIMENSION "$HIMAGE" .image
                else
                    convert -resize x$MAX_DIMENSION "$HIMAGE" .image
                fi
                rm -f "$LIMAGE"
                mv .image "$LIMAGE"
                echo " ---> thumbnail: "`jhead -c "$LIMAGE" | cut -d '"' -f 3 | cut -d ' ' -f 2`
            fi

            for LANGUAGE in $LANGUAGES; do
                # Add new images to list
                TITLES="titles-$LANGUAGE.text"
                echo "<table align=\"center\" border=1 cellspacing=0 cellpadding=3><tr><td align=\"center\" bgcolor=\"#444444\">" >> $LANGUAGE/.index
                echo "<a href=\"../$HIMAGE\"><img src=\"../$LIMAGE\" alt=\"$IMAGE\" title=\"$IMAGE\"></a>" >> $LANGUAGE/.index
                IMAGE_COMMENT=`grep -m1 -e "^$IMAGE:" "$TITLES"`
                if [ -z "$IMAGE_COMMENT" ]; then
                    echo "$IMAGE: untitled" >> "$TITLES"
                    IMAGE_COMMENT="untitled"
                else
                    IMAGE_COMMENT=`echo $IMAGE_COMMENT | sed "s%^$IMAGE:%%"`
                fi
                echo "<p align=\"center\"><b>$IMAGE_COMMENT</b><br><i>(Date: `date +"%F %R %Z" -r $HIMAGE`, Size: `du --si $HIMAGE | cut -f 1`)</i></p>" >> $LANGUAGE/.index
                echo "</tr></td></table><p>&nbsp;</p>" >> $LANGUAGE/.index
            done
        done

        for LANGUAGE in $LANGUAGES; do
            # Add footer
            footer >> $LANGUAGE/.index
            # Put new file online
            mv $LANGUAGE/.index $LANGUAGE/index.html
        done

        touch -r "$HIMAGE" .
        cd ..
    fi
done

# Create languages file
sort $ALL_LANGUAGES | uniq > languages
rm -f $ALL_LANGUAGES

# Now that the directory dates are set, fill in the main index file
echo "Create album indexes"
for LANGUAGE in `cat languages`; do
    mkdir -p $LANGUAGE
    echo " -> language $LANGUAGE"
    TITLE="Photos"

    header "$TITLE" > $LANGUAGE/.index

    echo "<table align=\"center\"><tr><td>" >> $LANGUAGE/.index
    ls -1tr | while read dir; do
        TITLES="$dir/titles-$LANGUAGE.text"
        if [ ! -r "$TITLES" ]; then
            # Default to English
            LANGUAGE_USED="en"
            TITLES="$dir/titles-$LANGUAGE_USED.text"
        else
            LANGUAGE_USED="$LANGUAGE"
        fi
        if [ -d "$dir/$LANGUAGE_USED" ] && [ -r "$TITLES" ] && [ -r "$dir/$LANGUAGE_USED/index.html" ]; then
            TITLE=`grep -e "^TITLE:" "$TITLES" | sed "s/^TITLE://"`
            echo -n "<h3><a href=\"../$dir/$LANGUAGE_USED\">$TITLE" >> $LANGUAGE/.index
            if [ "$LANGUAGE" != "$LANGUAGE_USED" ]; then
                echo -n " <img src=\"../flags/$LANGUAGE_USED.gif\" width=28 height=15 alt=\"[$LANGUAGE_USED]\" title=\"`cat $ROOT/names/$LANGUAGE_USED.text`\">" >> $LANGUAGE/.index
            fi
            echo "</a></h3>" >> $LANGUAGE/.index
            echo " --> linked $dir/$LANGUAGE_USED"
        fi
    done
    echo "</td></tr></table>" >> $LANGUAGE/.index
    footer >> $LANGUAGE/.index

    # Put new file online
    mv $LANGUAGE/.index $LANGUAGE/index.html
done

# Now that the directory dates are set, fill in the main index file
TITLE="Choose your language"
header "$TITLE" > $FILE
echo "<table align=\"center\"><tr><td>" >> $FILE
for LANGUAGE in `cat languages`; do
    echo "<a href=\"$LANGUAGE\"><img src=\"flags/$LANGUAGE.gif\" width=144 height=76 alt=\"`cat $ROOT/names/$LANGUAGE.text`\" title=\"`cat $ROOT/names/$LANGUAGE.text`\"></a>" >> $FILE
done
echo "</td></tr></table>" >> $FILE
echo "<p align=\"center\"><i>Generated: `date +"%F %R %Z" -r $FILE` using <a href=\"$PROGNAME\">this</a> script</i></p>" >> $FILE
footer >> $FILE

# Put new file online
mv $FILE index.html
